Portfolio: details popup window
belmeetmule/My-Portfolio pull request #2
Opened 2022-07-27 23:13 UTC by belmeetmule

### In this PR, I and my coding partner have done the following activities

- [ ] add popup window to the work section
- [ ] worked on js and DOM manipulation
- [ ] Worked on a little bit of css

2022-07-27 23:57 UTC, codecaiine requested changes
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good commits history :+1: 
- Good use of git-flow :+1: 
- Descriptive Pull request :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 23:57 UTC, codecaiine commented on index.html
>  <html lang="en">
- [ ] Good job so far :+1:  But please make sure that when your page is loading we can click on it :+1: 

![Screenshot from 2022-07-27 23-42-03](https://user-images.githubusercontent.com/6615394/181391256-80b7aa94-7dd9-4065-ae92-ca05a72ac8aa.png)

2022-07-27 23:57 UTC, codecaiine commented on scripts/pop-up.js
> +        </ul>
- [ ] Please make sure that your technologies is loaded from the project array because it part of project requirement :smile:

2022-07-27 23:57 UTC, codecaiine commented on index.html
> +        <div id="myModal" class="modal"></div>
- [ ] You pop up is different from the Figma template. Please make sure that both mobile et desktop version popup are similar to the Figma template cause you need to stick the template as much as possible :+1: 

check the screenshot below to see the difference:arrow_down: 

![Screenshot from 2022-07-27 23-43-56](https://user-images.githubusercontent.com/6615394/181391844-0fc0876c-2c65-4955-adf3-c014e023e4fd.png)

![Screenshot from 2022-07-27 23-55-06](https://user-images.githubusercontent.com/6615394/181391942-46885a9e-7336-4511-ae71-1e5488abecca.png)

2022-07-28 09:13 UTC, belmeetmule commented on index.html
>  <html lang="en">
> * [x]  Good job so far 👍  But please remove the background over your page  cause when your page is loading we can not click on it  we have to refresh over and over to be possible for us to remove the background over the page 👍
> 
> ![Screenshot from 2022-07-27 23-42-03](https://user-images.githubusercontent.com/6615394/181391256-80b7aa94-7dd9-4065-ae92-ca05a72ac8aa.png)
👍

2022-07-28 13:37 UTC, sumairq approved these changes
### Hi Team , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 13:44 UTC, merged